services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3307:3306
    volumes:
      - taskWorker_db:/var/lib/mysql
  # taskworker:
  #   build: .
  #   ports:
  #     - 3000:3000

volumes:
  taskWorker_db: